apiVersion: apps/v1
kind: Deployment
metadata:
  name: noto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noto
  template:
    metadata:
      labels:
        app: noto
    spec:
      containers:
        - name: noto
          image: k8s1:5000/noto:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: noto-svc
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: web
  selector:
    app: noto
