apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s1
      containers:
      - name: registry
        image: registry:latest
        env:
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
          value: "['*']"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        ports:
        - name: registry-port
          containerPort: 5000
      volumes:
      - name: registry-data
        hostPath:
          path: /var/lib/registry
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-front
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-front
  template:
    metadata:
      labels:
        app: registry-front
    spec:
      containers:
      - name: registry
        image: axelrindle/docker-registry-frontend:latest
        env:
        - name: REACT_APP_REGISTRY_API_URL
          value: http://192.168.10.101:5000
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registry-front-nodeport
  namespace: registry
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: registry-front
